// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWADVKc5p1cmOOVB1f0SzOkRSIrscpGvY',
    appId: '1:936300194507:web:e983d2bd4213d0adb3494e',
    messagingSenderId: '936300194507',
    projectId: 'story-app-dc5c4',
    authDomain: 'story-app-dc5c4.firebaseapp.com',
    storageBucket: 'story-app-dc5c4.firebasestorage.app',
    measurementId: 'G-LE3DZTTG0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9J8mw-m8tvU9vvQa_82kA7UpaFhXQVxQ',
    appId: '1:936300194507:android:02000395a3b1d71cb3494e',
    messagingSenderId: '936300194507',
    projectId: 'story-app-dc5c4',
    storageBucket: 'story-app-dc5c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_IXamcuLd2m0CvXVyJKpcFMjE2sAGUtg',
    appId: '1:936300194507:ios:d6d31d3100f8c5dfb3494e',
    messagingSenderId: '936300194507',
    projectId: 'story-app-dc5c4',
    storageBucket: 'story-app-dc5c4.firebasestorage.app',
    iosBundleId: 'com.example.pixiepen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_IXamcuLd2m0CvXVyJKpcFMjE2sAGUtg',
    appId: '1:936300194507:ios:d6d31d3100f8c5dfb3494e',
    messagingSenderId: '936300194507',
    projectId: 'story-app-dc5c4',
    storageBucket: 'story-app-dc5c4.firebasestorage.app',
    iosBundleId: 'com.example.pixiepen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWADVKc5p1cmOOVB1f0SzOkRSIrscpGvY',
    appId: '1:936300194507:web:319ac3803f5bfe85b3494e',
    messagingSenderId: '936300194507',
    projectId: 'story-app-dc5c4',
    authDomain: 'story-app-dc5c4.firebaseapp.com',
    storageBucket: 'story-app-dc5c4.firebasestorage.app',
    measurementId: 'G-DSDNFBG2ZF',
  );
}
